---
title: "Mixed Effects Models in Julia"
format-links: false
---

This website contains the course materials for an introduction to mixed effects models in Julia using [MixedModels.jl](https://juliastats.org/MixedModels.jl/v5/).

## Prerequisites

The material here assumes a basic proficiency with the Julia language, including a working Julia installation with Julia 1.9+.

## Installation of course materials

### Julia packages used in the examples

The source code for everything can be downloaded from [GitHub](https://github.com/palday/rit2025). After downloading the materials, you should install the necessary Julia packages.

::: {.callout-tip}
When copying and pasting into the Julia REPL, you don't need to remove the `julia>` prompt from the examples.
The Julia REPL will detect the prompt and strip it for you.
:::


Feel free to skip the `movielens_download` step -- the relevant examples are provided only to show scaling with very large datasets.

```sh
~/rit2025$ julia

julia> using Pkg

julia> Pkg.activate(".")
  Activating project at `~/rit2025`

julia> Pkg.instantiate()
< lots of output >

julia> using Rit2025

julia> Rit2025.movielens_download() # note: this is a very large dataset!
[ Info: Downloading data
[ Info: Extracting and saving ratings
[ Info: Extracting movies that are in the ratings table
[ Info: Extracting and saving README
2-element Vector{String}:
 "~/.julia/scratchspa" ⋯ 28 bytes ⋯ "3d4d5d689f47/data/ratings.arrow"
 "~/.julia/scratchspa" ⋯ 27 bytes ⋯ "-3d4d5d689f47/data/movies.arrow"

julia> exit()
```

If your receive a precompilation error for RCall or JellyMe4, you won't be able to use those packages, but should be able complete all other examples. The most likely cause of the precompilation error is a problem with RCall's configuration for using R from within Julia.

::: {.callout-important}
Please check that you have the most recent version of the materials directly before the course.
:::

### Rendering the course website

This repository uses [Quarto](https://quarto.org) with the Julia code execution supplied by [QuartoNotebookRunner.jl](https://github.com/PumasAI/QuartoNotebookRunner.jl/), which requires Quarto 1.5+.

As of early May 2024, Quarto 1.5 is only available as a preview release, which you'll need to [download from GitHub](https://github.com/quarto-dev/quarto-cli/releases). Under each release's "Assets", you can find platform-specific installers.

::: {.callout-tip}
You don't need to install or use quarto to view the course materials. Everything, including the example code, is visible on the website, with links to the underlying source code for the entire page.
:::


```sh
~/rit2025$ quarto preview

< lots of output >
```

<!-- 1. Basics of fitting a mixed model in Julia
    - Limitations of MixedModels.jl (what is not available)
3. Plotting functionality for mixed models
4. Integration with other packages Effects.jl, StandardizedPredictors.jl
5. The parametric bootstrap, random effects selection -->

*This page was rendered from git revision {{< git-rev short=true >}}.*
